/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;

/**
 *
 * @author DELL
 */
public class BillingSystem extends javax.swing.JFrame {

    double fi=0, se=0,re=0;
     char opr;
     String ans;
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tf = new javax.swing.JTextField();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        add = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        per = new javax.swing.JButton();
        blackspace = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        b = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        pb = new javax.swing.JTextField();
        w = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        td = new javax.swing.JTextField();
        tcm = new javax.swing.JTextField();
        gst = new javax.swing.JTextField();
        tc = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        ta = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        cal = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        tf.setEditable(false);
        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(tf);
        tf.setBounds(0, 0, 240, 30);

        bt6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6);
        bt6.setBounds(120, 100, 40, 40);

        bt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1);
        bt1.setBounds(0, 50, 40, 40);

        jButton3.setText("jButton1");
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 50, 40, 40);

        jButton4.setText("jButton1");
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 50, 40, 40);

        jButton5.setText("jButton1");
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 50, 40, 40);

        jButton6.setText("jButton1");
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 50, 40, 40);

        jButton7.setText("jButton1");
        jPanel1.add(jButton7);
        jButton7.setBounds(0, 50, 40, 40);

        jButton8.setText("jButton1");
        jPanel1.add(jButton8);
        jButton8.setBounds(0, 50, 40, 40);

        jButton9.setText("jButton1");
        jPanel1.add(jButton9);
        jButton9.setBounds(0, 50, 40, 40);

        jButton10.setText("jButton1");
        jPanel1.add(jButton10);
        jButton10.setBounds(0, 50, 40, 40);

        jButton11.setText("jButton1");
        jPanel1.add(jButton11);
        jButton11.setBounds(0, 50, 40, 40);

        jButton12.setText("jButton1");
        jPanel1.add(jButton12);
        jButton12.setBounds(0, 50, 40, 40);

        bt2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2);
        bt2.setBounds(60, 50, 40, 40);

        bt3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3);
        bt3.setBounds(120, 50, 40, 40);

        bt5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5);
        bt5.setBounds(60, 100, 40, 40);

        sub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub);
        sub.setBounds(200, 100, 40, 40);

        mul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mul.setText("*");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        jPanel1.add(mul);
        mul.setBounds(200, 160, 40, 40);

        bt8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8);
        bt8.setBounds(60, 160, 40, 40);

        bt9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9);
        bt9.setBounds(120, 160, 40, 40);

        bt0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0);
        bt0.setBounds(60, 220, 40, 40);

        add.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(200, 50, 40, 40);

        bt7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7);
        bt7.setBounds(0, 160, 40, 40);

        bt4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4);
        bt4.setBounds(0, 100, 40, 40);

        dot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });
        jPanel1.add(dot);
        dot.setBounds(120, 220, 40, 40);

        divide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        jPanel1.add(divide);
        divide.setBounds(200, 220, 40, 40);

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("c");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(0, 220, 40, 40);

        equal.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal);
        equal.setBounds(100, 260, 60, 70);

        per.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        per.setText("%");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });
        jPanel1.add(per);
        per.setBounds(200, 260, 40, 70);

        blackspace.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        blackspace.setText("<-");
        blackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackspaceActionPerformed(evt);
            }
        });
        jPanel1.add(blackspace);
        blackspace.setBounds(0, 260, 70, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 250, 340);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cb1.setText("samosa");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel2.add(cb1);
        cb1.setBounds(10, 20, 120, 30);

        cb3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cb3.setText("momos");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        jPanel2.add(cb3);
        cb3.setBounds(10, 100, 113, 30);

        cb4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cb4.setText("pav bhaji");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        jPanel2.add(cb4);
        cb4.setBounds(10, 140, 140, 30);

        cb5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cb5.setText("water");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        jPanel2.add(cb5);
        cb5.setBounds(10, 190, 120, 30);

        cb2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cb2.setText("burger");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        jPanel2.add(cb2);
        cb2.setBounds(10, 60, 110, 30);

        b.setEditable(false);
        b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b.setText("0");
        jPanel2.add(b);
        b.setBounds(170, 60, 70, 30);

        m.setEditable(false);
        m.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m.setText("0");
        jPanel2.add(m);
        m.setBounds(170, 100, 70, 30);

        pb.setEditable(false);
        pb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pb.setText("0");
        jPanel2.add(pb);
        pb.setBounds(170, 140, 70, 30);

        w.setEditable(false);
        w.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        w.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        w.setText("0");
        jPanel2.add(w);
        w.setBounds(170, 190, 70, 30);

        s.setEditable(false);
        s.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s.setText("0");
        jPanel2.add(s);
        s.setBounds(170, 20, 70, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Total delivery cost");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 90, 210, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total cost of milage");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 150, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total Cost of Items");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 20, 210, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("GST");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 220, 120, 20);

        td.setEditable(false);
        td.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        td.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        td.setText("0");
        jPanel3.add(td);
        td.setBounds(320, 90, 140, 35);

        tcm.setEditable(false);
        tcm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tcm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tcm.setText("0");
        jPanel3.add(tcm);
        tcm.setBounds(320, 150, 140, 35);

        gst.setEditable(false);
        gst.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gst.setText("0");
        jPanel3.add(gst);
        gst.setBounds(320, 210, 140, 35);

        tc.setEditable(false);
        tc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tc.setText("0");
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        jPanel3.add(tc);
        tc.setBounds(320, 20, 140, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(270, 20, 730, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(260, 20, 1010, 330);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel10.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Taxes");
        jPanel10.add(jLabel3);
        jLabel3.setBounds(50, 70, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Amount");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(50, 120, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Sub Total");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(50, 30, 90, 20);

        t.setEditable(false);
        t.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t.setText("Rs 0.00");
        jPanel10.add(t);
        t.setBounds(280, 70, 210, 28);

        ta.setEditable(false);
        ta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ta.setText("Rs 0.00");
        jPanel10.add(ta);
        ta.setBounds(280, 120, 210, 28);

        st.setEditable(false);
        st.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        st.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        st.setText("Rs 0.00");
        jPanel10.add(st);
        st.setBounds(280, 30, 210, 28);

        cal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cal.setText("Calculate");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });
        jPanel10.add(cal);
        cal.setBounds(910, 100, 200, 50);

        clr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clr.setText("Clear");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });
        jPanel10.add(clr);
        clr.setBounds(910, 20, 200, 50);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(30, 350, 1240, 160);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Online Billing System");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 530, 410, 40);

        jLabel8.setText("* with gst rate 18%");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(970, 570, 330, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       String s=tf.getText()+bt1.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
         String s=tf.getText()+bt2.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        String s=tf.getText()+bt3.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        String s=tf.getText()+bt4.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
         String s=tf.getText()+bt5.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
         String s=tf.getText()+bt6.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        String s=tf.getText()+bt7.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        String s=tf.getText()+bt8.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
         String s=tf.getText()+bt9.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
         String s=tf.getText()+bt0.getText();
       tf.setText(s);
    }//GEN-LAST:event_bt0ActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        if(!tf.getText().contains("."))
        {
            String k=tf.getText()+".";
            tf.setText(k);
        }
    }//GEN-LAST:event_dotActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       fi=Double.parseDouble(tf.getText());
       opr='+';
       tf.setText("");
      
    }//GEN-LAST:event_addActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        fi=Double.parseDouble(tf.getText());
       opr='-';
       tf.setText("");
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        fi=Double.parseDouble(tf.getText());
       opr='*';
       tf.setText("");
    }//GEN-LAST:event_mulActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        fi=Double.parseDouble(tf.getText());
       opr='/';
       tf.setText("");
    }//GEN-LAST:event_divideActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
       se=Double.parseDouble(tf.getText());
       if(opr=='+')
       {
           re=fi+se;
           tf.setText(String.valueOf(re));
       }
        if(opr=='-')
       {
           re=fi-se;
           tf.setText(String.valueOf(re));
       }
         if(opr=='*')
       {
           re=fi*se;
           tf.setText(String.valueOf(re));
       }
          if(opr=='/')
       {
           re=fi/se;
           tf.setText(String.valueOf(re));
       }
           if(opr=='%')
       {
           re=fi%se;
           tf.setText(String.valueOf(re));
       }
    }//GEN-LAST:event_equalActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       tf.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        fi=Double.parseDouble(tf.getText());
       opr='%';
       tf.setText("");
    }//GEN-LAST:event_perActionPerformed

    private void blackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackspaceActionPerformed
        String blackspace=null;
       if(tf.getText().length()>0);{
       StringBuilder stB=new StringBuilder(tf.getText());
       stB.deleteCharAt(tf.getText().length()-1);
       blackspace=stB.toString();
       tf.setText(blackspace);
    }
    }//GEN-LAST:event_blackspaceActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        if(cb4.isSelected())
       {
           pb.setEditable(true);
           pb.setText("");
           pb.requestFocus();
       }
       else
       {
           pb.setEditable(false);
           pb.setText("0");
       }
    }//GEN-LAST:event_cb4ActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        tf.setText("");
         s.setText("0");
          b.setText("0");
           m.setText("0");
            pb.setText("0"); 
            w.setText("0");
            tc.setText("0");
            t.setText("Rs 0.00");
             ta.setText("Rs 0.00");
              td.setText("0");
               tcm.setText("0");
                 gst.setText("0");
                  st.setText("Rs 0.00");
                   cb1.setSelected(false); 
                   cb2.setSelected(false); 
                   cb3.setSelected(false); 
                   cb4.setSelected(false); 
                   cb5.setSelected(false); 
                  
                   
                  
                
            
            
            
            
    }//GEN-LAST:event_clrActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
       if(cb1.isSelected())
       {
           s.setEditable(true);
           s.setText("");
           s.requestFocus();
       }
       else
       {
           s.setEditable(false);
           s.setText("0");
       }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
         if(cb2.isSelected())
       {
           b.setEditable(true);
           b.setText("");
           b.requestFocus();
       }
       else
       {
           b.setEditable(false);
           b.setText("0");
       }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        if(cb3.isSelected())
       {
           m.setEditable(true);
           m.setText("");
           m.requestFocus();
       }
       else
       {
           m.setEditable(false);
           m.setText("0");
       }
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
         if(cb5.isSelected())
       {
           w.setEditable(true);
           w.setText("");
           w.requestFocus();
       }
       else
       {
           w.setEditable(false);
           w.setText("0");
       }
    }//GEN-LAST:event_cb5ActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
       if(cb1.isSelected()|| cb2.isSelected()|| cb3.isSelected()||cb4.isSelected() ||cb5.isSelected() )
       {
           double sa=Double.parseDouble(s.getText())*10;
            double bu=Double.parseDouble(b.getText())*20;
             double mo=Double.parseDouble(m.getText())*25;
              double pbh=Double.parseDouble(pb.getText())*40;
               double wa=Double.parseDouble(w.getText())*20;
               double tot=sa+bu+mo+pbh+wa;
               double tde=tot*8/100;
               double mil=tde*50/100;
               double subtotal=tot+tde+mil;
               double ggst=subtotal*18/100;
               double totamount=subtotal+ggst;
               String item=String.valueOf(tot);
               tc.setText(item);
                String item1=String.valueOf(tde);
                td.setText( item1);
                String item2=String.valueOf(mil);
                tcm.setText( item2);
                String item3=String.valueOf(ggst);
                gst.setText( item3);
                String item4=String.valueOf(subtotal);
                st.setText( item4);
                String item5=String.valueOf(ggst);
                t.setText( item5);
                String item6=String.valueOf(totamount);
                ta.setText( item6);
                
       }
       else
       {
           tf.setText("plz select");
       }
    }//GEN-LAST:event_calActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField b;
    private javax.swing.JButton blackspace;
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton cal;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JButton clear;
    private javax.swing.JButton clr;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton equal;
    private javax.swing.JTextField gst;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField m;
    private javax.swing.JButton mul;
    private javax.swing.JTextField pb;
    private javax.swing.JButton per;
    private javax.swing.JTextField s;
    private javax.swing.JTextField st;
    private javax.swing.JButton sub;
    private javax.swing.JTextField t;
    private javax.swing.JTextField ta;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField tcm;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField w;
    // End of variables declaration//GEN-END:variables
}
